# Performance thresholds
WEAK_SUBJECT_THRESHOLD = 40
ADVANCED_THRESHOLD = 75

# Duration Defaults
DEFAULT_BEGINNER_DURATION = "6 Weeks"
DEFAULT_INTERMEDIATE_DURATION = "8 Weeks"
DEFAULT_ADVANCED_DURATION = "10 Weeks"

# Difficulty Defaults
DEFAULT_BEGINNER_DIFFICULTY = "Beginner"
DEFAULT_INTERMEDIATE_DIFFICULTY = "Intermediate"
DEFAULT_ADVANCED_DIFFICULTY = "Advanced"